/* Private, account-owned document workspace; no document blobs in localStorage. */
(()=>{
const endpoint='https://fklchtsxahepzfzgcqdp.supabase.co/functions/v1/prephub-documents';
let client,owner=null,revision=0,content=null,savedFiles=[],ui=null,timer,dirty=0,queue=Promise.resolve(),generation=0;
const key=()=>owner?'dpa_prephub_documents_draft:'+owner:null;
function draft(){try{const value=JSON.parse(localStorage.getItem(key()));return value?.owner===owner&&Date.now()-value.at<30*86400000?value:null;}catch{return null;}}
function stash(){if(!owner||!content)return;try{localStorage.setItem(key(),JSON.stringify({owner,content,revision,at:Date.now()}));}catch{}}
async function api(action,body={}){const expected=owner;const {data,error}=await client.auth.getSession();if(error||!expected||data.session?.user?.id!==expected)throw Error('Sign in to save your documents.');const result=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+data.session.access_token},body:JSON.stringify({action,...body})});const json=await result.json();if(owner!==expected)throw Error('Account changed. Reload your documents.');if(!result.ok)throw Error(json.error||'Could not save your documents. Retry.');return json;}
function edit(value){if(!owner){ui?.status('Sign in to save your documents.');return;}content=JSON.parse(JSON.stringify(value));dirty++;stash();clearTimeout(timer);timer=setTimeout(()=>save().catch(e=>ui?.status('Not saved · '+e.message)),750);ui?.status('Saving…');}
function save(){clearTimeout(timer);const operation=async()=>{if(!owner)throw Error('Sign in to save your documents.');while(dirty){const expected=owner,version=dirty,value=JSON.parse(JSON.stringify(content));const result=await api('save_workspace',{content:value,revision});if(owner!==expected)return;revision=result.revision;if(dirty===version){dirty=0;try{localStorage.removeItem(key());}catch{}}ui?.status('Saved');}};queue=queue.catch(()=>{}).then(operation);return queue;}
async function resumable(file,reservation,onProgress){if(!window.tus?.Upload)throw Error('The upload service has not loaded. Refresh and retry.');await new Promise((resolve,reject)=>{const upload=new window.tus.Upload(file,{endpoint:'https://fklchtsxahepzfzgcqdp.storage.supabase.co/storage/v1/upload/resumable',headers:{'x-signature':reservation.token},chunkSize:6*1024*1024,uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,retryDelays:[0,3000,5000,10000,20000],metadata:{bucketName:reservation.bucket,objectName:reservation.path,contentType:file.type||'application/pdf',cacheControl:'3600'},fingerprint:async()=>owner+':'+reservation.path,onProgress:(sent,total)=>onProgress(Math.round(sent/total*100)),onError:reject,onSuccess:resolve});upload.findPreviousUploads().then(previous=>{if(previous.length)upload.resumeFromPreviousUpload(previous[0]);upload.start();}).catch(reject);});}
const store={savedLabel:'Saved',edit,save,listFiles:async()=>savedFiles,async uploadFile(item,onProgress){await save();const expected=owner;const digest=await crypto.subtle.digest('SHA-256',await item.blob.arrayBuffer()),checksum=Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('');const reserved=await api('reserve',{personId:item.personId,category:item.category,slotId:item.slotId,name:item.name,type:item.type,size:item.size,checksum});if(reserved.saved)return reserved.file;onProgress(0);if(item.size>6*1024*1024)await resumable(new File([item.blob],item.name,{type:item.type}),reserved,onProgress);else{const uploaded=await client.storage.from(reserved.bucket).uploadToSignedUrl(reserved.path,reserved.token,item.blob,{contentType:item.type});if(uploaded.error)throw Error('Upload interrupted. Retry this file.');onProgress(100);}if(owner!==expected)throw Error('Account changed while uploading.');const completed=await api('complete',{id:reserved.id});savedFiles.push(completed.file);return completed.file;},async removeFile(id){await api('remove',{id});savedFiles=savedFiles.filter(f=>f.id!==id);},async viewFile(file){const popup=window.open('about:blank','_blank');if(popup)popup.opener=null;try{const result=await api('view',{id:file.id});if(popup)popup.location=result.url;else window.location.assign(result.url);}catch(e){popup?.close();throw e;}},send:data=>api('send',data)};
async function load(user){const round=++generation;owner=user?.id||null;revision=0;content=null;dirty=0;savedFiles=[];clearTimeout(timer);if(!owner){ui?.restore({});await ui?.reload();ui?.status('Sign in to save and restore your documents.');return;}try{const result=await api('load');if(round!==generation)return;revision=result.workspace?.revision||0;const local=draft(),recovered=local?.revision===revision?local.content:null;content=result.workspace?.content||recovered;if(recovered)content=recovered;if(!ui)ui=window.PrepHubDocumentsFactory(store);ui.restore(content||{});savedFiles=result.files;await ui.reload();if(recovered){edit(recovered);await save();}else ui.status(result.workspace?'Saved':'Ready to upload and save.');}catch(e){ui?.status('Could not load saved documents · '+e.message);}}
window.PrepHubDocuments={flush:()=>owner&&dirty?save():Promise.resolve()};
async function boot(){client=window.PrepHubAccount;if(!client)return;await window.PrepHubAccountReady;const session=await client.auth.getSession();await load(session.data.session?.user);client.auth.onAuthStateChange((event,session)=>{if(session?.user?.id!==owner)setTimeout(()=>load(session?.user),0);});window.addEventListener('online',()=>{if(dirty)save().catch(e=>ui?.status('Not saved · '+e.message));});document.querySelectorAll('#documents-workstation .dw-preview-note').forEach(e=>e.textContent='Documents save privately to your account. Lender download links expire in 7 days.');}
boot();
})();
