/* PrepHub Documents: design preview adapter keeps files on this browser only. */
window.PrepHubDocumentsFactory=function(store){
const root=document.getElementById('documents-workstation');if(!root)return null;
const q=s=>root.querySelector(s),all=s=>Array.from(root.querySelectorAll(s));
const kinds={identity:{title:'Identification',help:'Save a clear copy of your current ID if your lender requests it.'},pay:{title:'Recent Pay Stubs',help:'Start with about 30 days of pay history. Some lenders request 60 days. Include every page and enough pay periods to cover the requested dates.'},w2:{title:'W-2 Forms',help:'Start with two years of W-2 forms, including forms from every employer for each year.'},tax:{title:'Filed Tax Returns',help:'Start with two filed tax years, including all schedules. Add a third year only if your lender requests it.'},bank:{title:'Bank Statements',help:'Start with two recent monthly statements for every account used for funds. Add more months if requested. Include every page, even blank pages.'},contract:{title:'1099 Forms',help:'If requested, include all 1099 forms for each year. Forms alone do not replace complete filed tax returns.'},business:{title:'Current Business Records',help:'If requested, add a current year-to-date profit and loss statement and balance sheet.'},benefit:{title:'Benefit / Other Income Records',help:'If applicable, save the award letter or records for income you want considered.'},other:{title:'Additional Documents',help:'Add lender-requested records or a written explanation of a gap or concern.'}};
let people=[person()],active=0,files=[],lenderEmail='',pending=new Map(),messages=new Map(),busy=new Set(),databaseReady=false;
function person(p={}){const value={id:p.id||crypto.randomUUID(),name:p.name||'',lastName:p.lastName||'',mode:p.mode==='self'?'self':'w2',notes:p.notes||'',frequency:['weekly','biweekly','semimonthly','monthly'].includes(p.frequency)?p.frequency:'biweekly',payDays:p.payDays===60?60:30,taxYear:p.taxYear||new Date().getFullYear()-1,slots:p.slots||{}};ensureSlots(value);return value;}
function target(p,k){return k==='pay'?({weekly:p.payDays===60?9:5,biweekly:p.payDays===60?5:3,semimonthly:p.payDays===60?4:2,monthly:p.payDays===60?2:1}[p.frequency]):['w2','tax','bank','contract','business'].includes(k)?2:1;}
function slotLabel(p,k,i){return ['tax','w2','contract'].includes(k)?String(p.taxYear-i):k==='bank'?'Statement '+(i+1):k==='pay'?'Pay Stub '+(i+1):k==='business'?(i===0?'Year-to-date P&L':'Balance Sheet'):'Document '+(i+1);}
function ensureSlots(p){for(const k of Object.keys(kinds)){p.slots[k]=Array.isArray(p.slots[k])?p.slots[k].slice(0,24):[];while(p.slots[k].length<target(p,k))p.slots[k].push({id:k+':'+(p.slots[k].length+1),label:slotLabel(p,k,p.slots[k].length),period:''});if(['tax','w2','contract'].includes(k))p.slots[k].forEach((slot,i)=>slot.label=slotLabel(p,k,i));}}
function scoped(p,k,slot){return files.filter(f=>f.personId===p.id&&f.category===k&&f.slotId===slot.id);}

function name(p,i=people.indexOf(p)){return [p.name,p.lastName].filter(Boolean).join(' ').trim()||(i===0?'Your Documents':'Person 2');}
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function size(bytes){return bytes<1024*1024?(Math.max(1,Math.ceil(bytes/1024))+' KB'):((bytes/1024/1024).toFixed(1)+' MB');}
function categories(p){const core=p.mode==='self'?['identity','tax','bank']:['identity','pay','w2','bank'];const extra=p.mode==='self'?['contract','business','benefit','other']:['tax','benefit','other'];files.filter(f=>f.personId===p.id&&!core.includes(f.category)&&!extra.includes(f.category)).forEach(f=>{if(!extra.includes(f.category))extra.push(f.category);});return {core,extra};}
function metadata(){return {version:2,people:people.map(p=>({...p})),lenderEmail};}
function capture(){people[active].name=q('#dw-first-name').value.slice(0,60);people[active].lastName=q('#dw-last-name').value.slice(0,60);people[active].notes=q('#dw-notes').value.slice(0,2000);lenderEmail=q('#dw-lender-email').value.trim().slice(0,254);}
function edit(){capture();store.edit(metadata());renderPeople();renderSummary();}
function status(t){q('#dw-status').textContent=t;}
function renderPeople(){q('#dw-people').replaceChildren();people.forEach((p,i)=>{const b=node('button',name(p,i));b.type='button';b.dataset.dwPerson=String(i);b.setAttribute('aria-pressed',String(i===active));q('#dw-people').append(b);});q('#dw-add-person').hidden=people.length>=2;}
function activate(i){active=i;const p=people[i];ensureSlots(p);q('#dw-first-name').value=p.name;q('#dw-last-name').value=p.lastName;q('#dw-notes').value=p.notes;q('#dw-lender-email').value=lenderEmail;all('[data-dw-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.dwMode===p.mode)));renderPeople();renderCards();renderSummary();}
function renderCards(){const p=people[active],{core,extra}=categories(p);ensureSlots(p);q('#dw-records-title').textContent=name(p)+', organized.';q('#dw-cards').replaceChildren();[...core,...extra].forEach(k=>{
 const info=kinds[k],card=node(extra.includes(k)?'details':'section',undefined,'dw-card');card.dataset.dwCategory=k;
 if(extra.includes(k)&&files.some(f=>f.personId===p.id&&f.category===k))card.open=true;
 const head=node(extra.includes(k)?'summary':'div',undefined,'dw-card-head'),title=node('div');title.append(node('h3',info.title));if(extra.includes(k))title.append(node('small','If applicable or requested'));head.append(title);
 const complete=p.slots[k].filter(slot=>scoped(p,k,slot).length).length,badge=node('span',complete+' / '+p.slots[k].length+' saved','dw-badge');badge.dataset.saved=String(complete>0);head.append(badge);card.append(head,node('p',info.help));
 if(k==='pay'){const controls=node('div',undefined,'dw-slot-controls');for(const [field,label,options] of [['frequency','Paid',[['weekly','Weekly'],['biweekly','Every two weeks'],['semimonthly','Twice a month'],['monthly','Monthly']]],['payDays','History',[['30','30 days'],['60','60 days']]]]){const l=node('label',label),select=node('select');select.dataset.dwSetting=field;options.forEach(([value,text])=>{const o=node('option',text);o.value=value;o.selected=String(p[field])===value;select.append(o);});l.append(select);controls.append(l);}card.append(controls,node('small','Suggested slots cover the pay history above. Use the pay dates to confirm the full period is included.'));}
 if(k==='tax'||k==='w2'){const l=node('label',k==='w2'?'Most recent W-2 year':'Most recent filed tax year','dw-year-control'),select=node('select');select.dataset.dwSetting='taxYear';for(let year=new Date().getFullYear()-1;year>=new Date().getFullYear()-6;year--){const o=node('option',String(year));o.value=String(year);o.selected=p.taxYear===year;select.append(o);}l.append(select);card.append(l);}
 p.slots[k].forEach((slot,i)=>{const key=p.id+':'+slot.id,saved=scoped(p,k,slot),selected=pending.get(key)||[],row=node('div',undefined,'dw-slot'),heading=node('div',undefined,'dw-slot-heading');heading.append(node('span',String(i+1),'dw-slot-number'),node('strong',slot.label));const state=node('span',saved.length?'Saved · '+saved.length+' file'+(saved.length>1?'s':''):'Not added','dw-slot-state');heading.append(state);row.append(heading);
 const period=node('input');period.type='text';period.maxLength=80;period.value=slot.period||'';period.placeholder=k==='bank'?'Month / account, e.g. September · Checking':k==='pay'?'Pay date, e.g. September 27':'Optional label, e.g. Employer or business name';period.dataset.dwPeriod=slot.id;period.setAttribute('aria-label',info.title+' '+slot.label+' date or label');row.append(period);
 const actions=node('div',undefined,'dw-upload-row'),choose=node('label','Choose Files','dw-choose'),input=node('input');input.type='file';input.accept='.pdf,.jpg,.jpeg,.png';input.multiple=true;input.dataset.dwFiles=slot.id;input.setAttribute('aria-label','Choose files for '+info.title+' '+slot.label);input.disabled=!databaseReady||busy.has(key);choose.append(input);const upload=node('button',busy.has(key)?'Saving…':'Upload & Save','action');upload.type='button';upload.dataset.dwUpload=slot.id;upload.disabled=!databaseReady||!selected.length||busy.has(key);actions.append(choose,upload);row.append(actions);
 const st=node('div',messages.get(key)||(selected.length?selected.map(f=>f.name).join(', '):saved.length?store.savedLabel||'Saved on this browser · Design preview':'Add one or several files for this slot.'),'dw-upload-status');st.setAttribute('role','status');row.append(st);
 saved.forEach(f=>{const line=node('div',undefined,'dw-file'),label=node('div');label.append(node('strong',f.name),node('small',f.example?'Example file':size(f.size)));const buttons=node('div',undefined,'dw-file-actions');for(const action of ['View','Remove']){const btn=node('button',action);btn.type='button';btn.dataset.dwFile=f.id;btn.dataset.dwFileAction=action.toLowerCase();btn.disabled=busy.has(key);buttons.append(btn);}line.append(label,buttons);row.append(line);});card.append(row);
 });
 if(p.slots[k].length<24){const add=node('button',k==='tax'&&p.slots[k].length===2?'+ Add Third Tax Year (if requested)':k==='bank'?'+ Add Another Statement':k==='pay'?'+ Add Another Pay Stub':'+ Add Another '+(['w2','tax','contract'].includes(k)?'Year':'Document'),'textbtn dw-add-slot');add.type='button';add.dataset.dwAddSlot=k;card.append(add);}q('#dw-cards').append(card);
});}
function renderSummary(){const p=people[active],{core}=categories(p),total=core.reduce((n,k)=>n+target(p,k),0),ready=core.reduce((n,k)=>n+p.slots[k].slice(0,target(p,k)).filter(slot=>scoped(p,k,slot).length).length,0),percent=Math.round(ready/total*100);q('#dw-progress-count').textContent=ready+' of '+total;q('#dw-meter').setAttribute('aria-valuenow',String(percent));q('#dw-meter-fill').style.width=percent+'%';q('#dw-progress-copy').textContent=ready?ready+' of '+total+' starter upload slots have saved files.': 'Upload and save your first document to get started.';q('#dw-file-count').textContent=String(files.length);q('#dw-person-count').textContent=String(people.length);q('#dw-packet-size').textContent=files.length?(files.every(f=>f.example)?'Example files':size(files.reduce((n,f)=>n+f.size,0))):'0 MB';q('#dw-packet-people').replaceChildren();people.forEach((x,i)=>{const line=node('div',undefined,'dw-packet-person');line.append(node('span',name(x,i)),node('span',files.filter(f=>f.personId===x.id).length+' files'));q('#dw-packet-people').append(line);});const ok=files.length>0&&q('#dw-lender-email').validity.valid&&lenderEmail.length>0; q('#dw-review-packet').disabled=!databaseReady||busy.size>0||!ok;q('#dw-send-hint').textContent=ok?'Your saved household files are ready to review.':'Save documents and enter a lender email to review your packet.';}
async function validateFile(f){if(!f.size)throw Error('Choose a file that is not empty.');if(f.size>50*1024*1024)throw Error(f.name+' is over 50 MB. Split it into smaller documents.');const h=new Uint8Array(await f.slice(0,8).arrayBuffer());const pdf=h[0]===37&&h[1]===80&&h[2]===68&&h[3]===70&&h[4]===45,png=h[0]===137&&h[1]===80&&h[2]===78&&h[3]===71&&h[4]===13&&h[5]===10&&h[6]===26&&h[7]===10,jpg=h[0]===255&&h[1]===216&&h[2]===255;const type=pdf?'application/pdf':png?'image/png':jpg?'image/jpeg':null;if(!type)throw Error('Choose PDF, JPG or PNG files. '+f.name+' could not be recognized.');return type;}
async function upload(slotId){capture();const p=people[active],category=slotId.split(':')[0],key=p.id+':'+slotId,selection=pending.get(key)||[];if(!selection.length||busy.has(key))return;if(!p.name.trim()||!p.lastName.trim()){messages.set(key,'Enter this person’s first and last name before saving files.');renderCards();return;}busy.add(key);messages.set(key,'Saving your files…');renderCards();renderSummary();let added=0;try{store.edit(metadata());await store.save();for(const f of selection){const type=await validateFile(f);if(files.find(x=>x.personId===p.id&&x.slotId===slotId&&x.name===f.name&&x.size===f.size&&x.lastModified===f.lastModified))continue;if(files.length>=200)throw Error('This packet has 200 files. Remove unneeded files before adding more.');const item={id:crypto.randomUUID(),personId:p.id,category,slotId,period:p.slots[category].find(x=>x.id===slotId).period,name:f.name.slice(0,200),size:f.size,lastModified:f.lastModified,type,createdAt:new Date().toISOString(),blob:f};let saved=item;if(store.uploadFile)saved=await store.uploadFile(item,(percent)=>{messages.set(key,'Uploading '+f.name+' · '+percent+'%');const row=all('[data-dw-category]').find(x=>x.dataset.dwCategory===category);const st=Array.from(row?.querySelectorAll('.dw-upload-status')||[])[p.slots[category].findIndex(x=>x.id===slotId)];if(st)st.textContent=messages.get(key);});else await store.putFiles([item]);if(!files.some(x=>x.id===saved.id)){files.push(saved);added++;}}pending.delete(key);messages.set(key,added?(store.savedLabel||'Saved on this browser · Design preview'):'Already saved · No duplicate added');status(store.savedLabel||'Saved on this browser · Design preview');}catch(e){messages.set(key,(added?added+' file(s) saved. ':'')+'Not saved · '+e.message);status('Some files may still need saving · Retry this slot.');}finally{busy.delete(key);renderCards();renderSummary();}}
root.addEventListener('change',e=>{if(e.target.dataset.dwSetting){capture();const field=e.target.dataset.dwSetting;if(field==='taxYear'&&files.some(f=>f.personId===people[active].id&&['tax','w2','contract'].includes(f.category))){status('Remove saved year-specific files before changing the year, so documents stay correctly labeled.');renderCards();return;}people[active][field]=['taxYear','payDays'].includes(field)?Number(e.target.value):e.target.value;ensureSlots(people[active]);if(['frequency','payDays'].includes(field)){const p=people[active];while(p.slots.pay.length>target(p,'pay')){const slot=p.slots.pay.at(-1);if(scoped(p,'pay',slot).length||pending.get(p.id+':'+slot.id)?.length)break;p.slots.pay.pop();}}store.edit(metadata());renderCards();renderSummary();return;}const key=e.target.dataset.dwFiles;if(!key)return;const p=people[active],id=p.id+':'+key;pending.set(id,Array.from(e.target.files||[]));messages.delete(id);renderCards();});
root.addEventListener('input',e=>{if(e.target.dataset.dwPeriod){const slotId=e.target.dataset.dwPeriod,k=slotId.split(':')[0];people[active].slots[k].find(s=>s.id===slotId).period=e.target.value.slice(0,80);store.edit(metadata());}});
for(const id of ['#dw-first-name','#dw-last-name','#dw-notes','#dw-lender-email'])q(id).addEventListener('input',edit);
q('#dw-add-person').addEventListener('click',()=>{capture();if(people.length>=2)return;people.push(person());store.edit(metadata());activate(people.length-1);q('#dw-first-name').focus();});
root.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.dwAddSlot){const p=people[active],k=b.dataset.dwAddSlot;if(p.slots[k].length>=24)return;p.slots[k].push({id:k+':'+(p.slots[k].length+1),label:slotLabel(p,k,p.slots[k].length),period:''});store.edit(metadata());renderCards();renderSummary();return;}if(b.dataset.dwPerson!==undefined){capture();activate(Number(b.dataset.dwPerson));return;}if(b.dataset.dwMode){capture();people[active].mode=b.dataset.dwMode;store.edit(metadata());activate(active);return;}if(b.dataset.dwUpload){await upload(b.dataset.dwUpload);return;}if(b.dataset.dwFileAction){const f=files.find(x=>x.id===b.dataset.dwFile);if(!f)return;if(b.dataset.dwFileAction==='view'){try{await store.viewFile(f);}catch(error){status('Could not open file · '+error.message);}}else{try{await store.removeFile(f.id);files=files.filter(x=>x.id!==f.id);messages.delete(f.personId+':'+f.category);renderCards();renderSummary();status(store.savedLabel?'Removed from your saved packet.':'Removed from this preview packet.');}catch(error){status('Could not remove file · '+error.message);}}}});
q('#dw-save-notes').addEventListener('click',async()=>{edit();try{await store.save();status(store.savedLabel||'Saved on this browser · Design preview');}catch(e){status('Not saved · '+e.message);}});
q('#dw-review-packet').addEventListener('click',()=>{capture();if(!files.length||!q('#dw-lender-email').validity.valid||!lenderEmail)return;store.edit(metadata());q('#dw-review-email').textContent=lenderEmail;q('#dw-review-total').textContent=files.length+' saved document'+(files.length===1?'':'s')+' · '+size(files.reduce((n,f)=>n+f.size,0));q('#dw-review-files').replaceChildren();files.forEach(f=>{const p=people.find(p=>p.id===f.personId),line=node('div',undefined,'dw-file'),label=node('div');label.append(node('strong',f.name),node('small',name(p)+' · '+kinds[f.category].title+' · '+size(f.size)));line.append(label);q('#dw-review-files').append(line);});q('#dw-review-status').textContent='';q('#dw-send-confirm').disabled=false;q('#dw-review-dialog').showModal();});
for(const id of ['#dw-close-review','#dw-back-review'])q(id).addEventListener('click',()=>q('#dw-review-dialog').close());
let sendRequestId=null;
q('#dw-review-packet').addEventListener('click',()=>sendRequestId=crypto.randomUUID());
q('#dw-send-confirm').addEventListener('click',async()=>{if(!store.send){q('#dw-review-status').textContent='Preview only · No email was sent. The saved files and recipient above show the packet your lender would receive.';return;}const button=q('#dw-send-confirm');button.disabled=true;q('#dw-review-status').textContent='Preparing private links and sending…';try{await store.save();const result=await store.send({requestId:sendRequestId,recipient:lenderEmail,ids:files.map(f=>f.id),confirmed:true});if(!result.sent)throw Error('Email was not accepted.');q('#dw-review-status').textContent='Sent to '+result.recipient+' · Download links expire in 7 days.';}catch(error){q('#dw-review-status').textContent='Not sent · '+error.message;button.disabled=false;}});
if(store.uploadFile)q('#dw-example').hidden=true;
q('#dw-example').addEventListener('click',async()=>{if(!databaseReady||busy.size)return;try{capture();const p=people[active];store.edit(metadata());const keys=categories(p).core.slice(0,3),items=keys.filter(k=>!files.some(f=>f.personId===p.id&&f.category===k)).map(k=>{const blob=samplePDF(kinds[k].title);return {id:crypto.randomUUID(),personId:p.id,category:k,slotId:p.slots[k][0].id,name:'example-'+k.replace('_','-')+'.pdf',size:blob.size,lastModified:0,type:'application/pdf',createdAt:new Date().toISOString(),example:true,blob};});await store.putFiles(items);files.push(...items);activate(active);status('Example files saved on this browser · Design preview');}catch(e){status('Example could not be saved · '+e.message);}});
function samplePDF(label){const stream='BT /F1 18 Tf 50 740 Td (PREPHUB DESIGN PREVIEW) Tj 0 -30 Td /F1 12 Tf ('+label+') Tj 0 -25 Td (Example file only. No personal records.) Tj ET',objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Length '+stream.length+' >>\nstream\n'+stream+'\nendstream'];let text='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(text.length);text+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const xref=text.length;text+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+xref+'\n%%EOF';return new Blob([text],{type:'application/pdf'});}
function restore(data){people=data?.people?.length?data.people.slice(0,2).map(person):[person()];lenderEmail=String(data?.lenderEmail||'').slice(0,254);activate(Math.min(active,people.length-1));}
activate(0);store.listFiles().then(saved=>{files=saved.map(f=>({...f,category:['tax_recent','tax_prior'].includes(f.category)?'tax':f.category,slotId:f.slotId||(f.category==='tax_prior'?'tax:2':f.category==='tax_recent'?'tax:1':f.category+':1')})).filter(f=>people.some(p=>p.id===f.personId)&&kinds[f.category]);databaseReady=true;renderCards();renderSummary();status('Saved on this browser · Design preview');}).catch(e=>{status('File saving unavailable · '+e.message);renderCards();});return {restore,status,reload:async()=>{files=await store.listFiles();databaseReady=true;renderCards();renderSummary();}};
};

