(function(){
'use strict';
const root=document.getElementById('homebuyer-credit-staging'),q=s=>root.querySelector(s),all=s=>Array.from(root.querySelectorAll(s));
const url='https://fklchtsxahepzfzgcqdp.supabase.co',key='sb_publishable_TUIi5-8ISzGLtdFKxO-k6g_HCHz7nOk',sessionKey='prephub-workbook-session-v1';
const accountClient=window.supabase.createClient(url,key);
window.PrepHubAccount=accountClient;
let accountReady=Promise.resolve();
let saveTimer=null,saveInFlight=null,lastSave=null,editRevision=0,autoReady=false,authSettled=false;
class DirtyFields extends Set{add(key){super.add(key);editRevision++;scheduleAutoSave();return this;}}
let session=null,profile=null,pending=null,active='reports',dirty=new DirtyFields(),reports=[],state={debts:[],debt_notes:'',flags:[],flag_notes:'',questions:[],own_questions:'',checklist:[],pathway_tasks:{},action_checks:{},credit_review:null,review_income:'',review_debt:'',analysis:'',report_notes:'',pathway_step:'reports',dispute_bureau:'Experian',dispute_item:'',dispute_reason:'',dispute_evidence:'',dispute_confirm:false,dispute_draft:'',disputes_sent:'',followup_baseline:[],followup_notes:'',progress_scores:[],progress_anchor:'',progress_excluded:[],progress_history:[],department_checks:{}};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const notice=t=>{q('#prep-global-status').textContent=t;q('#wb-save-status').textContent=t;const status=q('#wb-letter-status');if(status)status.textContent=t;};
const redact=t=>t.replace(/\b\d{3}[- ]?\d{2}[- ]?\d{4}\b/g,'[identifier removed]').replace(/\b\d{10,19}\b/g,'[account number removed]');
async function request(action,data={},auth=true){if(auth){await accountReady;const current=await accountClient.auth.getSession();session=current.data?.session||null;if(current.error||!session){signIn();throw new Error('Reconnect your PrepHub account to save. Your edits are still here.');}if(session.expires_at*1000<Date.now()+60000){const renewed=await accountClient.auth.refreshSession();if(renewed.error||!renewed.data?.session)throw new Error('Your PrepHub session has ended. Return to My PrepHub to reconnect before saving; your edits are still here.');session=renewed.data.session;}}
const r=await fetch(url+'/functions/v1/'+(auth?'prephub-credit-workbook':'prephub-workbook-auth'),{method:'POST',headers:{apikey:key,'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+session.access_token}:{})},body:JSON.stringify({action,...data})});const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||d.message||'This could not be completed.');return d;}
function setSaveStatus(text){const status=q('#prep-autosave-status');if(status)status.textContent=text;}
function syncSessionControls(){if(!authSettled){['#wb-login','#wb-signout','#prep-account-login','#prep-account-logout'].forEach(id=>q(id).hidden=true);setSaveStatus('Loading your account…');return;}const connected=!!session;q('#wb-login').hidden=connected;q('#wb-signout').hidden=!connected;q('#prep-account-login').hidden=connected;q('#prep-account-logout').hidden=!connected;if(!connected){autoReady=false;clearTimeout(saveTimer);setSaveStatus('Sign in to save your preparation');}else setSaveStatus('Autosave connected');}
function scheduleAutoSave(){if(!session||!autoReady||!dirty.size)return;clearTimeout(saveTimer);setSaveStatus('Changes waiting to save…');saveTimer=setTimeout(()=>save().catch(error=>{setSaveStatus('Not saved · Use Save to retry');notice(error.message);}),900);}
function signIn(){if(window.PrepHubSignIn)window.PrepHubSignIn();}
async function authenticated(fn){await accountReady;return fn();}
function workbookId(){if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,n=>n.toString(16).padStart(2,'0'));return h.slice(0,4).join('')+'-'+h.slice(4,6).join('')+'-'+h.slice(6,8).join('')+'-'+h.slice(8,10).join('')+'-'+h.slice(10).join('');}
function renderProfileRequest(r){all('[data-plan]').forEach(b=>{const requested=!!r&&r.plan_key===b.dataset.plan;b.dataset.requested=String(requested);b.disabled=requested;b.textContent=requested?'Requested':'I Want to Start This Plan';});}
async function load(){const data=await request('load');profile=data.profile;reports=data.reports||[];const server=data.workbook?.content||{};for(const k of Object.keys(state))if(!dirty.has(k)&&server[k]!==undefined)state[k]=server[k];q('#wb-account-label').textContent=(profile.first_name||'Your')+'’s PrepHub credit preparation';q('#wb-account-status').textContent='Signed in · Save preparation changes to your profile. Report files are private.';syncSessionControls();renderProfileRequest(profile.credit_plan_request);renderAll();renderPathway();renderSavedReports();autoReady=true;setSaveStatus('All changes saved');scheduleAutoSave();}
q('#wb-login').addEventListener('click',()=>{if(!session)signIn();else q('#wb-account-status').textContent='Your PrepHub profile is connected.';});
q('#wb-signout').addEventListener('click',async()=>{await accountClient.auth.signOut();session=null;profile=null;reports=[];state={debts:[],debt_notes:'',flags:[],flag_notes:'',questions:[],own_questions:'',checklist:[],pathway_tasks:{},action_checks:{},credit_review:null,review_income:'',review_debt:'',analysis:'',report_notes:'',pathway_step:'reports',dispute_bureau:'Experian',dispute_item:'',dispute_reason:'',dispute_evidence:'',dispute_confirm:false,dispute_draft:'',disputes_sent:'',followup_baseline:[],followup_notes:'',progress_scores:[],progress_anchor:'',progress_excluded:[],progress_history:[],department_checks:{}};dirty.clear();localStorage.removeItem(sessionKey);q('#wb-account-label').textContent='Sign in to save your work to your PrepHub profile.';q('#wb-account-status').textContent='Signed out. Personal preparation information has been cleared from this page.';q('#wb-login').textContent='Sign In to Save';syncSessionControls();renderProfileRequest(null);renderAll();});
all('[data-wb-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
q('#wb-email-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;q('#wb-login-status').textContent='Sending your code…';try{const d=await request('send_login',{email:q('#wb-email').value},false);q('#wb-login-status').textContent=d.message;q('#wb-code-form').hidden=false;q('#wb-code').focus();}catch(err){q('#wb-login-status').textContent=err.message;}finally{button.disabled=false;}});
q('#wb-code-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;q('#wb-login-status').textContent='Opening your preparation…';try{const d=await request('verify_login',{email:q('#wb-email').value,code:q('#wb-code').value},false);const connected=await accountClient.auth.setSession({access_token:d.session.access_token,refresh_token:d.session.refresh_token});if(connected.error)throw connected.error;session=connected.data.session;await load();q('#wb-login-dialog').close();const next=pending;pending=null;if(next)await next();}catch(err){q('#wb-login-status').textContent=err.message;}finally{button.disabled=false;}});
const titles={reports:'Gather My Three Credit Reports',flags:'Analyze My Reports for Discrepancies',disputes:'Start My Disputes',followup:'Track Your Progress',balances:'My Balances & Monthly Payments',questions:'My Homebuyer Questions'};
all('[data-wb-panel]').forEach(panel=>{const host=q('#wb-content-'+panel.dataset.wbPanel);if(host){host.append(panel);panel.hidden=false;}});
function open(panel){const button=q('[data-workbook="'+panel+'"]'),host=q('#wb-content-'+panel);const expanded=button.getAttribute('aria-expanded')!=='true';all('[data-workbook]').forEach(b=>{b.setAttribute('aria-expanded','false');q('#wb-content-'+b.dataset.workbook).hidden=true;});active=panel;if(['reports','flags','disputes','followup'].includes(panel)){state.pathway_step=panel;dirty.add('pathway_step');}q('#wb-title').textContent=titles[panel];if(expanded){button.setAttribute('aria-expanded','true');host.hidden=false;host.append(q('#wb-save-status'));notice('');}}
all('[data-workbook]').forEach(b=>b.addEventListener('click',()=>open(b.dataset.workbook)));
const categories=[['credit_card','Credit card'],['installment','Installment loan'],['student','Student loan'],['alimony','Alimony'],['child_support','Child support']];
function addDebt(value={}){if(state.debts.length>=30){notice('You can list up to 30 accounts or obligations.');return;}state.debts.push({id:workbookId(),type:'credit_card',name:'',balance:'',payment:'',...value});dirty.add('debts');renderDebts();}
function renderDebts(){const container=q('#wb-debt-rows');container.replaceChildren();state.debts.forEach((debt,index)=>{const div=document.createElement('div');div.className='wb-debt-row';const fields=document.createElement('div');fields.className='wb-debt-fields';function field(labelText,k,type){const label=document.createElement('label');label.textContent=labelText;const input=type==='select'?document.createElement('select'):document.createElement('input');if(type==='select'){categories.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;input.append(o);});}else{input.type=type;if(type==='number'){input.min='0';input.max='1000000';input.step='any';input.inputMode='decimal';}else input.maxLength=80;}input.value=debt[k];input.addEventListener('input',()=>{debt[k]=input.value;dirty.add('debts');totals();});label.append(input);fields.append(label);}field('Account or obligation','type','select');field('Nickname / company','name','text');field('Current balance ($)','balance','number');field('Required monthly payment ($)','payment','number');const remove=document.createElement('button');remove.type='button';remove.className='textbtn';remove.textContent='Remove this entry';remove.addEventListener('click',()=>{state.debts.splice(index,1);dirty.add('debts');renderDebts();});div.append(fields,remove);container.append(div);});totals();}
function totals(){let balances=0,credit=0,support=0;state.debts.forEach(d=>{const b=Number(d.balance)||0,p=Number(d.payment)||0;if(b>=0)balances+=b;if(p>=0){if(['alimony','child_support'].includes(d.type))support+=p;else credit+=p;}});q('#wb-total-balances').textContent=money(balances);q('#wb-total-credit').textContent=money(credit);q('#wb-total-support').textContent=money(support);}
q('#wb-add-debt').addEventListener('click',()=>addDebt());
const flags=[['charge_off','Charge-off details need review','Compare ownership, balance, status, and reporting dates with your records.'],['bankruptcy','Bankruptcy information needs review','Compare the reported dates and status with the court records.'],['lien','Lien or public-record information needs review','Check the source, ownership, dates, and whether the information belongs in this report.'],['identity','Names, addresses, or accounts I don’t recognize','Compare personal details and account ownership with your records.'],['balance','Balances or credit limits that look incorrect','Compare with recent statements and reporting dates.'],['payment','Payments incorrectly shown late or unpaid','Check dates, payment confirmations, and account statements.'],['duplicate','The same debt appears more than once','Check creditor names and whether entries describe the same obligation.'],['closed','Closed or paid accounts show an unexpected status','Check payoff letters, closure records, and the last update.'],['collection','Collection details need verification','Check the creditor, amount, ownership, and supporting records.'],['inquiry','An inquiry I don’t recognize','Compare with credit applications you authorized.'],['age','Dates or the age of an item need review','Ask a qualified specialist to check reporting dates and applicable limits.'],['student','Student loan balance, status, or payment needs review','Compare servicer statements and your repayment arrangement.']];
const questions=[['priorities','What should I work on first in my credit preparation?'],['score','Which mortgage score and DPA target should I confirm with a lender?'],['student','How will my student loan payment be treated for the mortgage?'],['cards','How should I balance card payments with saving for my first home?'],['errors','Which report items need supporting records or a specialist review?'],['budget','Do my monthly obligations fit the housing payment I’m considering?']];
function checks(container,list,keyName){const c=q(container);c.replaceChildren();list.forEach(([id,title,copy])=>{const div=document.createElement('div');div.className='wb-flag';const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=state[keyName].includes(id);input.addEventListener('change',()=>{state[keyName]=input.checked?[...new Set([...state[keyName],id])]:state[keyName].filter(k=>k!==id);dirty.add(keyName);callPrompt();});label.append(input,document.createTextNode(title));div.append(label);if(copy){const small=document.createElement('small');small.textContent=copy;div.append(small);}c.append(div);});}
[['#wb-debt-notes','debt_notes'],['#wb-own-questions','own_questions']].forEach(([id,k])=>q(id).addEventListener('input',()=>{state[k]=q(id).value;dirty.add(k);callPrompt();}));
function callPrompt(){const selected=questions.filter(([id])=>state.questions.includes(id)).map(([,t])=>t);q('#wb-call-prompt').textContent='“I’m preparing to buy my first home. Please review my saved credit preparation. '+(selected.length?selected.join(' '):'What should I work on first?')+(state.own_questions?' My own questions: '+state.own_questions:'')+'”';}
function renderDepartmentChecks(){const counters={};all('[data-check]').filter(e=>e.dataset.check!=='credit').forEach(e=>{const area=e.dataset.check,key=area+'-'+(counters[area]=(counters[area]||0)+1);e.checked=!!state.department_checks[key];e.dispatchEvent(new Event('change',{bubbles:true}));});}
function renderAll(){renderDepartmentChecks();renderDebts();checks('#wb-question-list',questions,'questions');q('#wb-debt-notes').value=state.debt_notes;q('#wb-own-questions').value=state.own_questions;callPrompt();renderPathway();renderSavedReports();}
function snapshot(){const debts=state.debts.map(d=>({id:d.id,type:d.type,name:redact(d.name).slice(0,80),balance:d.balance===''?null:Number(d.balance),payment:d.payment===''?null:Number(d.payment)}));if(debts.some(d=>[d.balance,d.payment].some(v=>v!==null&&(!Number.isFinite(v)||v<0||v>1000000))))throw new Error('Enter valid non-negative balances and monthly payments.');return {...state,debts,debt_notes:redact(state.debt_notes),flag_notes:redact(state.flag_notes),own_questions:redact(state.own_questions),checklist:[(q('[data-task="reports"]')?.checked??!!state.checklist[0]),(q('[data-support-check="balances"]')?.checked??!!state.checklist[1]),(q('[data-task="flags"]')?.checked??!!state.checklist[2]),(q('[data-support-check="questions"]')?.checked??!!state.checklist[3])],pathway_tasks:{...state.pathway_tasks,...Object.fromEntries(all('[data-task]').map(e=>[e.dataset.task,e.checked]))}};}
async function save(){clearTimeout(saveTimer);if(saveInFlight){await saveInFlight;if(!dirty.size)return lastSave;}let succeeded=false;saveInFlight=(async()=>{const revision=editRevision,content=snapshot();notice('Saving to your PrepHub profile…');setSaveStatus('Saving…');const data=await request('save',{content});if(editRevision===revision)dirty.clear();lastSave=data;succeeded=true;const time=new Date(data.updated_at).toLocaleTimeString();notice('Saved to your PrepHub profile · '+time);setSaveStatus(dirty.size?'New changes waiting to save…':'Saved · '+time);return data;})();try{return await saveInFlight;}finally{saveInFlight=null;if(succeeded&&dirty.size)scheduleAutoSave();}}
const departmentCounters={};all('[data-check]').filter(e=>e.dataset.check!=='credit').forEach(e=>{const area=e.dataset.check,k=area+'-'+(departmentCounters[area]=(departmentCounters[area]||0)+1);e.addEventListener('change',()=>{if(!!state.department_checks[k]!==e.checked){state.department_checks[k]=e.checked;dirty.add('department_checks');}});});
all('[data-wb-save]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;try{await authenticated(save);}catch(err){notice(err.message);}finally{b.disabled=false;}}));
q('#wb-request-call').addEventListener('click',async()=>{if(!q('#wb-call-consent').checked){notice('Please confirm you want a callback about your saved preparation work.');return;}try{await authenticated(async()=>{await save();await request('call',{consent:true,questions:q('#wb-call-prompt').textContent});notice('Your callback request and saved preparation context have been recorded for specialist follow-up.');});}catch(err){notice(err.message);}});
['experian','equifax','transunion'].forEach(bureau=>{const div=document.createElement('section');div.className='wb-bureau';const title=document.createElement('h3');title.textContent=bureau[0].toUpperCase()+bureau.slice(1);const input=document.createElement('input');input.type='file';input.accept='application/pdf,image/png,image/jpeg';input.setAttribute('aria-label','Upload my '+title.textContent+' credit report');const status=document.createElement('p');status.className='cp-small';status.setAttribute('role','status');const saveButton=document.createElement('button');saveButton.type='button';saveButton.className='action';saveButton.textContent='Upload & Save '+title.textContent+' Report';const saved=document.createElement('p');saved.id='wb-saved-'+bureau;saved.className='cp-small';const uploadLabel=document.createElement('label');uploadLabel.textContent='Choose My '+title.textContent+' Credit Report';uploadLabel.append(input);div.append(title,uploadLabel,saveButton,status,saved);q('#wb-bureaus').append(div);
input.addEventListener('change',()=>{status.textContent=input.files[0]?'Report selected. Upload and save it to your profile.':'';});
saveButton.addEventListener('click',async()=>{const file=input.files[0];if(!validFile(file)){status.textContent='Choose a PDF, PNG, or JPG up to 10 MB.';return;}saveButton.disabled=true;try{await authenticated(async()=>{await request('load');status.textContent='Uploading your private report…';const ext=file.type==='application/pdf'?'pdf':file.type==='image/png'?'png':'jpg';const path=session.user.id+'/'+workbookId()+'.'+ext;const uploaded=await fetch(url+'/storage/v1/object/prephub-credit-reports/'+path,{method:'POST',headers:{apikey:key,Authorization:'Bearer '+session.access_token,'Content-Type':file.type},body:file});if(!uploaded.ok)throw new Error('Upload failed. Please try again.');await request('report',{bureau,storage_path:path,extracted_text:'',reviewed_by_customer:false});await load();status.textContent='Report saved privately. Use Analyze My Reports when you are ready.';input.value='';});}catch(err){status.textContent=err.message;}finally{saveButton.disabled=false;}});
});
function validFile(f){return !!f&&f.size>0&&f.size<=10485760&&['application/pdf','image/png','image/jpeg'].includes(f.type);}
async function extract(file,progress){let worker=null,pdf=null;async function ocr(image){if(!worker)worker=await Tesseract.createWorker('eng',1,{workerPath:'https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/worker.min.js',corePath:'https://cdn.jsdelivr.net/npm/tesseract.js-core@7.0.0',langPath:'https://tessdata.projectnaptha.com/4.0.0',logger:m=>{if(m.status==='recognizing text')progress('Reading report text… '+Math.round(m.progress*100)+'%');}});const {data}=await worker.recognize(image);return data.text;}
try{if(file.type!=='application/pdf')return await ocr(file);progress('Opening PDF…');const pdfjs=await import('https://cdn.jsdelivr.net/npm/pdfjs-dist@5.6.205/build/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@5.6.205/build/pdf.worker.mjs';pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),isEvalSupported:false}).promise;if(pdf.numPages>100)throw new Error('Split this report into files of 100 pages or fewer before reading.');let text='';for(let n=1;n<=pdf.numPages;n++){progress('Reading page '+n+' of '+pdf.numPages);const page=await pdf.getPage(n);const content=await page.getTextContent();let pageText=content.items.map(i=>i.str||'').join(' ');if(pageText.trim().length<40){const viewport=page.getViewport({scale:1.5}),canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;pageText=await ocr(canvas);}text+='\nPage '+n+'\n'+pageText;page.cleanup();}return text;}finally{if(worker)await worker.terminate();if(pdf)await pdf.destroy();}}
function renderSavedReports(){let total=0;['experian','equifax','transunion'].forEach(b=>{const count=reports.filter(r=>r.bureau===b).length;if(count)total++;q('#wb-saved-'+b).textContent=count?count+' report'+(count===1?'':'s')+' saved in your profile.':'No report saved for this bureau yet.';});const input=q('[data-check="credit"]');const completed=total===3;state.checklist[0]=completed;state.pathway_tasks.reports=completed;if(input&&input.checked!==completed){input.checked=completed;input.dispatchEvent(new Event('change',{bubbles:true}));}if(q('[data-report-completion]'))q('[data-report-completion]').textContent=completed?'Task complete':total+'/3 reports saved';renderFollowup();}
window.PrepHubWorkbook={reload:load,requestPlan:async(planKey)=>authenticated(async()=>{const d=await request('plan',{plan_key:planKey});if(!d.saved||!d.request)throw new Error('Your request could not be saved. Please try again.');if(profile)profile.credit_plan_request=d.request;renderProfileRequest(d.request);return d;})};

const pathwayFields={'wb-dispute-bureau':'dispute_bureau','wb-dispute-item':'dispute_item','wb-dispute-reason':'dispute_reason','wb-dispute-evidence':'dispute_evidence','wb-dispute-draft':'dispute_draft'};
function renderPathway(){all('[data-wb-action]').forEach(e=>e.checked=!!state.action_checks[e.dataset.wbAction]);for(const [id,key] of Object.entries(pathwayFields))q('#'+id).value=state[key]||'';q('#wb-dispute-confirm').checked=state.dispute_confirm;all('[data-task]').forEach(e=>{const saved=state.pathway_tasks[e.dataset.task];if(saved!==undefined)e.checked=!!saved;else if(e.dataset.task==='flags')e.checked=!!state.checklist[2];});if(q('[data-support-check="balances"]'))q('[data-support-check="balances"]').checked=!!state.checklist[1];if(q('[data-support-check="questions"]'))q('[data-support-check="questions"]').checked=!!state.checklist[3];renderFollowup();renderCreditReview();renderDisputeFindings();}
function localDate(value=new Date()){const d=value instanceof Date?value:new Date(value);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function checkpointDate(anchor,days){const d=new Date(anchor+'T12:00:00');d.setDate(d.getDate()+days);return localDate(d);}
function progressEvents(){const excluded=new Set(state.progress_excluded||[]);return [...(state.progress_scores||[]).map(s=>({...s,kind:'score'})),...reports.filter(r=>!excluded.has(r.id)).map(r=>({id:r.id,date:localDate(r.created_at),bureau:r.bureau,kind:'report'}))].filter(e=>/^\d{4}-\d{2}-\d{2}$/.test(e.date)).sort((a,b)=>a.date.localeCompare(b.date));}
function renderFollowup(){const events=progressEvents(),anchor=state.progress_anchor||events[0]?.date||localDate(),today=localDate();const summary=q('#wb-progress-summary');summary.replaceChildren(reviewNode('strong','Your starting point: '+new Date(anchor+'T12:00:00').toLocaleDateString()),reviewNode('p',events.length?'Your saved scores and report upload dates appear below.':'Add your starting score or upload your first report. Your timeline will begin from your first entry.'));const timeline=q('#wb-progress-timeline');timeline.replaceChildren();for(let month=0;month<=12;month++){const marker=checkpointDate(anchor,month*30),previous=month?checkpointDate(anchor,(month-1)*30):null;const card=document.createElement('li');card.className='wb-progress-marker'+(marker===today?' current':marker<today?' past':'');card.append(reviewNode('strong',month?'Month '+month+' · Day '+month*30:'Starting Point'),reviewNode('time',new Date(marker+'T12:00:00').toLocaleDateString()));const entries=events.filter(e=>month?e.date>previous&&e.date<=marker:e.date<=marker);entries.forEach(e=>{const row=reviewNode('p',(e.kind==='score'?e.score+' · '+(e.model||'Model not specified'):'Report uploaded')+' · '+e.bureau+' · '+new Date(e.date+'T12:00:00').toLocaleDateString(),'wb-progress-event');card.append(row);});if(!entries.length)card.append(reviewNode('p',marker<=today?'Add a score or an updated report for this check-in.':'Your next 30-day progress checkpoint.','cp-small'));timeline.append(card);}q('#wb-progress-date').value=q('#wb-progress-date').value||today;const done=events.some(e=>e.date>=checkpointDate(anchor,330))&&today>=checkpointDate(anchor,360);if(q('[data-task="followup"]'))q('[data-task="followup"]').checked=done;state.pathway_tasks.followup=done;if(q('[data-followup-completion]'))q('[data-followup-completion]').textContent=done?'12 months tracked':'12-month tracker';const checks=all('[data-task]');if(q('[data-count="credit"]'))q('[data-count="credit"]').textContent=checks.filter(e=>e.checked).length+' of 4 complete';}
async function saveProgress(message){renderFollowup();await accountReady;if(session){try{await save();q('#wb-progress-status').textContent=message+' Saved to your PrepHub profile.';}catch(e){q('#wb-progress-status').textContent=e.message;}}else q('#wb-progress-status').textContent=message+' Not saved yet. Connect your PrepHub profile to save this timeline.';}
q('#wb-add-progress-score').addEventListener('click',async()=>{const score=Number(q('#wb-progress-score').value),date=q('#wb-progress-date').value;if(!Number.isInteger(score)||score<300||score>850||!/^\d{4}-\d{2}-\d{2}$/.test(date)||date>localDate()){q('#wb-progress-status').textContent='Enter a score from 300 to 850 and a valid score date up to today.';return;}if(state.progress_scores.length>=120){q('#wb-progress-status').textContent='Start a fresh timeline to add more score entries.';return;}state.progress_scores.push({id:workbookId(),score,date,bureau:q('#wb-progress-bureau').value,model:q('#wb-progress-model').value.trim().slice(0,60),source:'manual'});dirty.add('progress_scores');q('#wb-progress-score').value='';await saveProgress('Score added.');});
q('#wb-progress-fresh').addEventListener('click',async()=>{state.progress_history=[{scores:state.progress_scores,anchor:state.progress_anchor,excluded:state.progress_excluded,archived_at:new Date().toISOString()},...(state.progress_history||[])].slice(0,3);state.progress_scores=[];state.progress_anchor=localDate();state.progress_excluded=reports.map(r=>r.id);['progress_history','progress_scores','progress_anchor','progress_excluded'].forEach(k=>dirty.add(k));await saveProgress('Fresh timeline started. Your report files remain saved and the previous timeline is archived.');});
function captureReportScores(review){if(!Array.isArray(review.report_scores))return;for(const s of review.report_scores){if(!Number.isInteger(s.score)||s.score<300||s.score>850)continue;const report=reports.find(r=>r.bureau===s.bureau);if(!report||state.progress_excluded.includes(report.id))continue;const id='report-score-'+report.id+'-'+s.score_model;if(state.progress_scores.some(v=>v.id===id))continue;state.progress_scores.push({id,score:s.score,date:localDate(report.created_at),bureau:s.bureau,model:s.score_model||'Report model not specified',source:'report',report_id:report.id,score_date:s.score_date});dirty.add('progress_scores');}renderFollowup();}
for(const [id,key] of Object.entries(pathwayFields))q('#'+id).addEventListener('input',()=>{state[key]=q('#'+id).value;dirty.add(key);if(key==='disputes_sent'){state.followup_baseline=reports.map(r=>r.id);dirty.add('followup_baseline');renderFollowup();}});
q('#wb-dispute-confirm').addEventListener('change',()=>{state.dispute_confirm=q('#wb-dispute-confirm').checked;dirty.add('dispute_confirm');});
all('[data-task]').forEach(e=>e.addEventListener('change',()=>{state.pathway_tasks[e.dataset.task]=e.checked;dirty.add('pathway_tasks');}));
all('[data-support-check]').forEach(e=>e.addEventListener('change',()=>{state.checklist[e.dataset.supportCheck==='balances'?1:3]=e.checked;dirty.add('checklist');}));
q('#wb-upload-updated').addEventListener('click',()=>{open('reports');q('[data-workbook="reports"]').scrollIntoView({behavior:'smooth',block:'start'});notice('Upload an updated report from whichever bureau you have. Your earlier reports remain saved. Choose free analysis to read any reported score.');});
async function scanUploadedReports(){await load();const latest=[];for(const bureau of ['experian','equifax','transunion']){const report=reports.find(r=>r.bureau===bureau);if(report)latest.push(report);}if(!latest.length)throw new Error('Upload at least one report before requesting analysis.');let readable=0;const failures=[];for(let i=0;i<latest.length;i++){const report=latest[i];notice('Scanning '+report.bureau[0].toUpperCase()+report.bureau.slice(1)+' · '+(i+1)+' of '+latest.length+' uploaded reports…');try{const downloaded=await accountClient.storage.from('prephub-credit-reports').download(report.storage_path);if(downloaded.error||!downloaded.data)throw new Error('Could not open this report.');const blob=downloaded.data;const file=new File([blob],report.storage_path.split('/').pop(),{type:blob.type});const text=redact(await extract(file,t=>notice(t))).slice(0,60000);await request('report',{bureau:report.bureau,storage_path:report.storage_path,extracted_text:text,reviewed_by_customer:false});if(text.trim())readable++;else failures.push(report.bureau);}catch{failures.push(report.bureau);}}if(!readable)throw new Error('The uploaded files could not be read. Try a clearer report or choose a plan for specialist review.');await load();if(failures.length)notice('Some report pages could not be read. Your review will explain the missing information.');}
async function pathwayAi(kind){if(!aiConfigured){notice('PREPHUB is not connected yet.');return;}const button=q(kind==='analysis'?'#wb-ai-analysis':'#wb-ai-dispute');if(kind==='analysis'&&!reports.length){notice('Upload at least one report, then choose Analyze My Reports.');return;}if(kind==='dispute'&&(!state.dispute_confirm||!state.dispute_bureau||!state.dispute_item.trim()||!state.dispute_reason.trim())){notice('Describe a specific discrepancy and confirm you reviewed it before drafting a letter.');return;}button.disabled=true;button.setAttribute('aria-busy','true');try{await authenticated(async()=>{await save();if(kind==='analysis')await scanUploadedReports();notice(kind==='analysis'?'PREPHUB is preparing your itemized review…':'PREPHUB is preparing your dispute letter draft…');const question=kind==='analysis'?'Analyze the available report text from whichever bureaus I have uploaded. Do not require all three. Provide an itemized numbered review. For each item include: bureau and account nickname, reported issue and evidence, whether it is a possible discrepancy or a credit concern requiring a non-dispute action, affected scoring factor, how it may affect my credit profile, priority with reasoning, documents to verify, and my next action. Distinguish accurate negative information from possible errors. Do not invent score-point ranges. In the score-change field say Estimate unavailable without a validated score-specific simulator. Explain whether correcting a confirmed error might help, have no effect, or have uncertain effects. Do not add impacts together. Note missing bureaus and uncertain OCR readings. End with the top three priorities.':('Draft a concise factual consumer dispute letter to '+state.dispute_bureau+' about this item: '+state.dispute_item+'. My stated discrepancy and requested correction: '+state.dispute_reason+'. Supporting records: '+state.dispute_evidence+'. Use my stated facts only; use placeholders for missing name, address, dates, report reference, and recipient address. Do not invent claims or identifiers. Request investigation and correction if appropriate. Do not claim I sent this letter.').slice(0,2000);const d=kind==='analysis'?await request('analyze'):await request('ask',{question});const field=kind==='analysis'?'analysis':'dispute_draft';if(kind==='analysis'){state.credit_review=d.review;captureReportScores(d.review);dirty.add('credit_review');renderCreditReview();renderDisputeFindings();}state[field]=kind==='analysis'?d.review.summary:d.answer;if(kind==='dispute')q('#wb-dispute-draft').value=state[field];dirty.add(field);await save();notice('Prepared and saved. Review the text against your records before using it.');});}catch(err){notice(err.message);}finally{button.disabled=!aiConfigured;button.setAttribute('aria-busy','false');}}
all('[data-wb-action]').forEach(e=>e.addEventListener('change',()=>{state.action_checks[e.dataset.wbAction]=e.checked;dirty.add('action_checks');}));
all('[data-wb-next]').forEach(button=>button.addEventListener('click',async()=>{const next=button.dataset.wbNext,previous=state.pathway_step;button.disabled=true;try{await accountReady;state.pathway_step=next;dirty.add('pathway_step');if(session)await save();const target=q('[data-workbook="'+next+'"]');if(target.getAttribute('aria-expanded')!=='true')open(next);target.scrollIntoView({behavior:'smooth',block:'start'});target.focus();if(!session)notice('Connect your PrepHub account to save your notes and current step.');}catch(err){state.pathway_step=previous;notice(err.message);}finally{button.disabled=false;}}));

const reviewCategories={collection:'Collections',charge_off:'Charge-offs',medical_collection:'Medical collections',bankruptcy:'Bankruptcies',delinquent_student_loan:'Delinquent student loans',late_payment:'Late-payment accounts'};
function reviewNode(tag,text,cls){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;return el;}
function renderCreditReview(){const host=q('#wb-credit-review'),review=state.credit_review;if(!review||!Array.isArray(review.items)){host.replaceChildren(reviewNode('p','Your findings will appear after analysis. No findings have been generated yet.','cp-small'));return;}host.replaceChildren();host.append(reviewNode('h3','Your Credit Findings'),reviewNode('p',review.summary));const counts=document.createElement('div');counts.className='wb-review-counts';for(const [category,label] of Object.entries(reviewCategories)){const count=review.items.filter(i=>Array.isArray(i.categories)&&i.categories.includes(category)).length;const tile=document.createElement('div');tile.append(reviewNode('strong',String(count)),reviewNode('span',label));counts.append(tile);}host.append(counts,reviewNode('p','Counts reflect findings in the readable uploaded reports. Categories can overlap; the same account across bureaus is counted once. Check each finding against the original report.','cp-small'));if(!review.items.length)host.append(reviewNode('p','No supported items in these categories were identified. This does not establish mortgage preparation.'));review.items.forEach(item=>{const card=document.createElement('article');card.className='wb-review-item';card.append(reviewNode('h4',item.title),reviewNode('p',(item.bureaus||[]).join(' · '),'cp-small'));[['The finding',item.evidence],['Why it matters',item.credit_impact],['Your next step',item.next_step],['Homebuyer support',item.homebuyer_support]].forEach(([label,text])=>{const line=document.createElement('p');line.append(reviewNode('strong',label+': '),document.createTextNode(text||''));card.append(line);});host.append(card);});host.append(reviewNode('p',review.limitations,'cp-small'));}
function disputeReviewBureaus(item){const bureaus=[...new Set((Array.isArray(item.bureaus)?item.bureaus:[]).filter(b=>['experian','equifax','transunion'].includes(b)))];return bureaus.length?bureaus:[null];}
function renderDisputeFindings(){
 const host=q('#wb-dispute-findings'),review=state.credit_review;host.replaceChildren();
 if(!review||!Array.isArray(review.items)){host.append(reviewNode('p','Your potential letter count will appear after your free AI analysis.'));return;}
 const letters=review.items.reduce((sum,item)=>sum+disputeReviewBureaus(item).length,0);
 host.append(reviewNode('h3','You have '+letters+' potential dispute letter'+(letters===1?'':'s')+' to review.'),reviewNode('p','Every negative or flagged finding is available for review, even when the analysis has not identified an error. One potential draft per item and reporting bureau; choose the bureau when it is missing. Several items can be combined in one bureau letter. Confirm what may be inaccurate or incomplete before drafting. These are review opportunities, not confirmed errors or guaranteed removals.','cp-small'));
 review.items.forEach(item=>{
  const card=document.createElement('article');card.className='wb-review-item';
  const possible=item.dispute_status==='possible_inaccuracy';
  card.append(reviewNode('h4',item.title),reviewNode('p',(item.categories||[]).map(c=>reviewCategories[c]||'Other concern').join(' · '),'cp-small'),reviewNode('strong',possible?'Possible discrepancy to verify':item.dispute_status==='credit_concern'?'Negative item · Review for possible dispute':'Needs verification · Review for possible dispute'),reviewNode('p',item.dispute_reason||item.evidence),reviewNode('p',item.next_step));
  const button=reviewNode('button','I Would Like to Dispute This','action secondary');button.type='button';button.setAttribute('aria-expanded','false');
  const note=document.createElement('div');note.className='wb-dispute-note';note.hidden=true;note.style.cssText='margin-top:12px;padding:16px;border:1px solid rgba(8,31,92,.14);border-radius:12px;background:rgba(244,247,252,.82);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);box-shadow:0 8px 28px rgba(8,31,92,.10)';
  const label=reviewNode('label','Why would you like to dispute this?');const reason=document.createElement('textarea');reason.rows=3;reason.maxLength=2000;reason.placeholder='Briefly explain what may be wrong or incomplete.';reason.style.cssText='display:block;width:100%;box-sizing:border-box;margin:8px 0 12px;padding:10px;border:1px solid #cbd7e6;border-radius:8px;background:rgba(255,255,255,.8)';label.append(reason);
  const bureauLabel=reviewNode('label','Reporting bureau');const bureauSelect=document.createElement('select');bureauSelect.style.cssText='display:block;margin:8px 0 12px;max-width:100%';
  const known=disputeReviewBureaus(item).filter(Boolean);const choices=known.length?known:['experian','equifax','transunion'];
  if(!known.length){const placeholder=reviewNode('option','Choose the reporting bureau');placeholder.value='';bureauSelect.append(placeholder);}
  choices.forEach(b=>{const text=b==='transunion'?'TransUnion':b[0].toUpperCase()+b.slice(1);const option=reviewNode('option',text);option.value=text;bureauSelect.append(option);});bureauLabel.append(bureauSelect);
  const prepare=reviewNode('button','Prepare My Dispute','action');prepare.type='button';const status=reviewNode('p','','cp-small');status.setAttribute('role','status');
  button.addEventListener('click',()=>{note.hidden=!note.hidden;button.setAttribute('aria-expanded',String(!note.hidden));if(!note.hidden)reason.focus();});
  prepare.addEventListener('click',async()=>{
   if(!reason.value.trim()){status.textContent='Add a quick reason before continuing.';reason.focus();return;}
   if(!bureauSelect.value){status.textContent='Choose the reporting bureau.';bureauSelect.focus();return;}
   prepare.disabled=true;status.textContent='Saving your dispute preparation…';
   try{await authenticated(async()=>{
    state.dispute_bureau=bureauSelect.value;state.dispute_item=(item.title||'').slice(0,100);state.dispute_reason=reason.value.trim();state.dispute_evidence='';state.dispute_confirm=false;state.dispute_draft='';
    ['dispute_bureau','dispute_item','dispute_reason','dispute_evidence','dispute_confirm','dispute_draft'].forEach(k=>dirty.add(k));
    await save();for(const [id,key] of Object.entries(pathwayFields))q('#'+id).value=state[key]||'';q('#wb-dispute-confirm').checked=false;
    const plan=q('[data-plan="self"]');q('#cp-plan-options').hidden=false;plan.closest('.cp-plan').scrollIntoView({behavior:'smooth',block:'center'});plan.focus();status.textContent='Your reason is saved. Continue with the Instant Prep Plan.';
   });}catch(error){status.textContent=error.message||'Your reason could not be saved. Please try again.';}finally{prepare.disabled=false;}
  });
  note.append(label,bureauLabel,prepare,status);card.append(button,note);
  host.append(card);
 });
}
q('#wb-ai-dispute-review').addEventListener('click',async()=>{const b=q('#wb-ai-dispute-review');b.disabled=true;b.setAttribute('aria-busy','true');try{await pathwayAi('analysis');renderDisputeFindings();}finally{b.disabled=!aiConfigured;b.setAttribute('aria-busy','false');}});
all('[data-review-plans]').forEach(b=>b.addEventListener('click',()=>{q('#cp-plan-options').hidden=false;q('#cp-plan-options').scrollIntoView({behavior:'smooth',block:'start'});}));
all('[data-dispute-plan]').forEach(b=>b.addEventListener('click',()=>{q('#cp-plan-options').hidden=false;const card=q('[data-plan="'+b.dataset.disputePlan+'"]').closest('.cp-plan');card.scrollIntoView({behavior:'smooth',block:'center'});q('[data-plan="'+b.dataset.disputePlan+'"]').focus();}));

q('#wb-ai-analysis').addEventListener('click',()=>pathwayAi('analysis'));q('#wb-ai-dispute').addEventListener('click',()=>pathwayAi('dispute'));
let aiConfigured=false;
function setAiStatus(text){all('[data-pathway-ai-status]').forEach(e=>e.textContent=text);}
request('capabilities',{},false).then(d=>{aiConfigured=d.ai_configured===true;['#wb-ai-analysis','#wb-ai-dispute','#wb-ai-dispute-review'].forEach(id=>q(id).disabled=!aiConfigured);const status=aiConfigured?'PREPHUB connected · Scans your uploaded reports when you choose Analyze, then reviews the available text and workbook notes.':'PREPHUB is prepared, but its server API key is not configured yet. You can organize and save your workbook now.';setAiStatus(status);}).catch(()=>{['#wb-ai-analysis','#wb-ai-dispute','#wb-ai-dispute-review'].forEach(id=>q(id).disabled=true);setAiStatus('PREPHUB could not connect right now. Please try again.');});
renderAll();
accountClient.auth.onAuthStateChange((event,next)=>{session=next;syncSessionControls();if(next&&event==='SIGNED_IN')setTimeout(()=>load().catch(error=>{q('#wb-account-status').textContent=error.message;setSaveStatus('Could not load saved preparation');}),0);});
accountReady=(async()=>{const current=await accountClient.auth.getSession();session=current.data?.session||null;syncSessionControls();if(session){const lead=new URLSearchParams(location.search).get('lead')||localStorage.getItem('dpa_prephub_lead_id');if(lead){const claimed=await accountClient.rpc('claim_prephub_lead',{p_lead_id:lead});if(claimed.error)throw claimed.error;}}if(!session){let legacy=null;try{legacy=JSON.parse(localStorage.getItem(sessionKey)||'null');}catch{}if(legacy?.access_token&&legacy?.refresh_token){const restored=await accountClient.auth.setSession({access_token:legacy.access_token,refresh_token:legacy.refresh_token});session=restored.data?.session||null;if(session)localStorage.removeItem(sessionKey);}}})();
window.PrepHubAccountReady=accountReady;
accountReady.then(()=>{authSettled=true;syncSessionControls();if(session)load().catch(err=>{q('#wb-account-status').textContent=err.message;});}).catch(async()=>{const current=await accountClient.auth.getSession();session=current.data?.session||null;if(!current.error){authSettled=true;syncSessionControls();}setSaveStatus('Account could not finish loading · Refresh to retry');});

// Keep the shared credit-request interface consistent on older department-page copies.
(function setupPlanRequestUI(){
 const legacy=!q('[data-plan-note]');
 q('#cp-profile-request')?.remove();
 if(!legacy)return;
 const style=document.createElement('style');
 style.textContent="\n#homebuyer-credit-staging .cp-plan{position:relative}\n#homebuyer-credit-staging .cp-request-note{position:absolute;z-index:5;left:18px;right:18px;bottom:72px;padding:14px 36px 14px 14px;border:1px solid rgba(8,31,92,.14);border-radius:12px;background:rgba(255,255,255,.88);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px);box-shadow:0 8px 28px rgba(8,31,92,.12);color:#081f5c;font-size:12px;line-height:1.45}\n#homebuyer-credit-staging .cp-request-note p{font-size:12px;min-height:0;margin:5px 0 0}\n#homebuyer-credit-staging .cp-request-note button{position:absolute;right:9px;top:7px;border:0;background:transparent;color:#081f5c;font-size:22px;line-height:1;cursor:pointer;padding:4px}\n#homebuyer-credit-staging [data-plan][data-requested=\"true\"]{opacity:1;background:#edf3f8;color:#081f5c;border-color:#cbd7e6;cursor:default}\n";
 root.append(style);
 q('.prep-brand .brand')?.remove();
 const logo=q('.prep-brand .logo');if(logo){logo.style.fontSize='32px';logo.style.lineHeight='1.1';logo.style.letterSpacing='-1px';}
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let textNode;while((textNode=walker.nextNode())){if(textNode.textContent.includes('PrepHub AI'))textNode.textContent=textNode.textContent.replaceAll('PrepHub AI','PREPHUB');if(textNode.textContent==='HOMEBUYER PATHWAY PREMIUM')textNode.textContent='HOMEBUYER PATHWAY PLUS';}
 all('[data-plan]').forEach(button=>{
  const note=document.createElement('div');note.className='cp-request-note';note.dataset.planNote=button.dataset.plan;note.hidden=true;
  note.innerHTML='<button type="button" aria-label="Close request message">×</button><strong>Request received</strong><p>Your plan request is saved. We’ll call you to discuss the next steps.</p>';
  note.querySelector('button').addEventListener('click',()=>{note.hidden=true;});button.after(note);
 });
 root.addEventListener('click',async event=>{
  const button=event.target.closest('[data-plan]');if(!button)return;
  event.preventDefault();event.stopImmediatePropagation();
  if(button.disabled||button.dataset.requested==='true')return;
  const note=q('[data-plan-note="'+button.dataset.plan+'"]');
  button.disabled=true;button.textContent='Requesting…';note.hidden=true;
  try{await window.PrepHubWorkbook.requestPlan(button.dataset.plan);note.querySelector('strong').textContent='Request received';note.querySelector('p').textContent='Your plan request is saved. We’ll call you to discuss the next steps.';}
  catch(error){note.querySelector('strong').textContent='Request not saved';note.querySelector('p').textContent=error.message||'Please try again.';}
  finally{if(button.dataset.requested!=='true'){button.disabled=false;button.textContent='I Want to Start This Plan';}note.hidden=false;}
 },true);
})();
})();
